### ISSUE TITLE
How to enable firestorm?

### ISSUE THREAD

**Issue by vedantroy** [That3Percent/firestorm#3]
How do I enable firestorm? Is there an example in the README? An environment variable I have to set?

**Comment by That3Percent** [comment]
Yes, there is an example in the README.
No, there is not an environment variable you need to set.

First, you need to instrument: [Instrumenting](https://github.com/That3Percent/firestorm#instrumenting)
Then enable profiling with an added feature in Cargo: [Profiling](https://github.com/That3Percent/firestorm#profiling)
