### ISSUE TITLE
Windows support? 

### ISSUE THREAD

**Issue by Boscop** [That3Percent/firestorm#4]
Thanks for making this. Does it work on Windows (8.1)?

**Comment by That3Percent** [comment]
I've tried this on Windows 10 and it works fine there. I can't think of any reason it wouldn't work on 8.1, but if you try it and there is some problem then feel free to re-open this issue.

**Comment by Boscop** [comment]
Thanks :) 
Btw, is it possible to generate flamegraphs without instrumenting, from a sampling profiler's captures?
E.g. I use the Very Sleepy profiler, it can also export captures as CSV.

**Comment by That3Percent** [comment]
Not with this library. There are some other libraries that can do this, but I have not used them. I think there were some recommendations when I introduced the library on reddit you might be interested in, but in my experience, Windows support is not ideal: https://www.reddit.com/r/rust/comments/lkvlya/introducing_the_firestorm_profiler/

**Comment by Boscop** [comment]
Thanks. Btw, what are the pros & cons of using firestorm vs tracy (via https://crates.io/crates/tracy-client and instrumenting with https://crates.io/crates/profiling).
Because both require instrumenting (and the `profiling` crate supports a couple backends but not firestorm), so I have to make a choice :)

**Comment by That3Percent** [comment]
I haven't looked into `tracy` very deeply. So, I would encourage you to figure out what is best for you.

One note from an API design perspective, the `tracy` docs state:

> Simply depending on crates in this repository is sufficient for tracy to be enabled at program startup

I think this is a huge mistake that all of the intrusive profilers that I've seen make (except `firestorm`). This has a lot of implications when you want to figure out how to enable profiling for lots of dependencies (possibly transitively). It moves the profiler being used into the public surface API of the crate, makes the code messy, and introduces many problems. I write a bit about it here when comparing to `flame`: [https://www.reddit.com/r/rust/comments/lkvlya/introducing_the_firestorm_profiler/gnnwr0l?utm_source=share&utm_medium=web2x&context=3](https://www.reddit.com/r/rust/comments/lkvlya/introducing_the_firestorm_profiler/gnnwr0l?utm_source=share&utm_medium=web2x&context=3)

That being said I'm sure that `tracy` does something great that `firestorm` does not currently. So, do what's best for you.
